#!/usr/bin/env bash

remote_url="$(git config --get --local remote.origin.url)"

if [[ "$remote_url" =~ "paymaya" ]]; then
    git config --local user.email "edward.samson@paymaya.com"
elif [[ "$remote_url" =~ "voyager" ]]; then
    git config --local user.email "edward.samson@paymaya.com"
fi

